// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzcjdmorxrlzpvkdotxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Y2pkbW9yeHJsenB2a2RvdHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTg3MzgsImV4cCI6MjA2NDU5NDczOH0.IGD0pab2IPT91J0nmzVov9IGJMQCG9SRrpFzHyNEliQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);